### ISSUE TITLE
Unable to make connection to Growatt 3000S with ShineWIFI-S

### ISSUE THREAD

**Issue by SaiedTaki** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#16]
Hi Wouter,
Thank you for making this possible first of all. I hope you might know what could be causing the connection issue of the add-in to my inverter.
Unable to establish connection

**Comment by SaiedTaki** [comment]
![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/124246426/eaa0bb9f-1a0a-4988-82a8-3b3c30d07f72)

**Comment by dixi83** [comment]
The ShineWIFI-S is not a modbus device... you need to connect a modbus serial server or a usb-modbus converter...

**Comment by WouterTuinstra** [comment]
A ShineWIFI-S is not supported with this integration it expects to communicate directly to the device.
