### ISSUE TITLE
Integration process in HA needed

### ISSUE THREAD

**Issue by Mosconi8** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#19]
Hi,
after installation of HACS and Growatt-lacal-modbus i can't find the UI.
So it would be nice to have some short installation steps.
Thanx

**Comment by Saentist** [comment]
Go to: Settings >devices and services > click on add ...

**Comment by Mosconi8** [comment]
The growatt local modbus module is already in the settings -> devises.
But i can't find the UI for the modbus settings.

**Comment by jurriaanbos** [comment]
Hi @WouterTuinstra, I just added the repo but there is no automatic config flow starting. Like Mosconi I can not find a way to edit the config now.
