### ISSUE TITLE
Unable to add Repo

### ISSUE THREAD

**Issue by Lu-Fi** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#3]
HASS says invalid repo.
How can i add it for testing

**Comment by WouterTuinstra** [comment]
How have you added the repo?
There are 2 options:

1. Manual add the `growatt_local` folder to your homeassistant config folder `custom_components/growatt_local` 
2. By using HACS and following steps to add this repo: https://hacs.xyz/docs/faq/custom_repositories
