### ISSUE TITLE
Error configuration flow

### ISSUE THREAD

**Issue by wayne83m** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#30]
hi,
i get an error when i want to add the integration in HA.

HA-Infos:
Core
2024.2.2
Supervisor
2024.02.0
Operating System
11.5
Frontend
20240207.1

error msg:
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

translated from german:
its not possible to load the configuration flow:  {"message":"Invalid handler specified"}

**Comment by WouterTuinstra** [comment]
Hi,
Have you checked the HA system logs?
Potentially you have that the requirements are not automaticly installed pymodbus is a required library

**Comment by Saentist** [comment]
https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/issues/27
