### ISSUE TITLE
Support writing any parameter value to Growatt SPF6000ES (offgrid/hybrid)

### ISSUE THREAD

**Issue by wire67** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#38]
What effort would it take to support writing any parameter value to Growatt SPF6000ES (offgrid/hybrid) https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/pull/18? I think it could be a simple event trigger with a `data` pair register/value, https://www.home-assistant.io/docs/automation/trigger/#event-trigger. That way it remains very flexible. Just not sure where to start, I have seen @WouterTuinstra has already added a button for writing a parameter export on/off on another device but wasn't able to easily understand how things work to make it more generalised.

**Comment by wire67** [comment]
thank you @WouterTuinstra I managed to do that with `actions` and your comment lead me to the right path after failing with every other solution.
For anyone else, those are the full steps to write any variable in SPF6000ES or any other modbus device:
- edit `/homeassistant/configuration.yaml` 
- add a `modbus` entry, there must be at least one sensor or switch it seems. Doc: https://www.home-assistant.io/integrations/modbus/
```modbus:
  - name: modbus_hub
    type: serial
    port: /dev/ttyUSB1
    baudrate: 9600
    bytesize: 8
    method: rtu
    parity: N
    stopbits: 1
    switches:
      - name: "BAT First"
        address: 1
        command_on: 0 # SbU
        command_off: 3 # SUb
        verify: # read back 
```
- use `/developer-tools/action` to test the action and copy it's YAML, for instance
```action: modbus.write_register
data:
  hub: modbus_hub
  address: 1
  slave: 1
  value: 0
```
- add a script entry that can then easily be called to perform the action(s), in `/config/script/dashboard`, paste the previously test YAML
- call this `Scripts: yourscriptname` from `Automations`

**Comment by dartyukh-afk** [comment]
Hi @wire67, @WouterTuinstra , is it possible to control in Home Assistant all most popular settings of Growatt SPF6000ES (like Source: SBU/SUB/SOL/UTI; Charging:  CSO/SNU/OSO; pointing to/back to battery percentage; charging current)?  May be there is already forked solution etc.?

**Comment by wire67** [comment]
@dartyukh-afk it's technically possible, I have a fork/branch for SUB/SBU here, which I'm successfully using. However I'm not familiar enough with the source code to add more settings.
